[package]
name = "printdb"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.8", features = ["mysql"]}
clap = { version = "3.1.12", features = ["derive"]}
rpassword = "6.0"
